### ISSUE TITLE
Burp Errors

### ISSUE THREAD

**Issue by Teicu** [CompassSecurity/jwt-scanner#1]
Hi all, 

any idea how to fix this?  
 
Macbook / Burp Suite Professional 2024.3.1.2 

Thanks

	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
java.lang.IllegalArgumentException: HTTP service cannot be null
	at burp.Zij2.ZI(Unknown Source)
	at burp.Zij2.sendRequest(Unknown Source)
	at burp.Zij2.sendRequest(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zx_5.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy58.sendRequest(Unknown Source)
	at burp.Zk78.sendRequest(Unknown Source)
	at BurpExtension.JWTScanCheck.activeAudit(JWTScanCheck.java:59)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zx_5.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy56.activeAudit(Unknown Source)
	at burp.Zm23.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
java.lang.NullPointerException: Cannot invoke "burp.api.montoya.scanner.AuditResult.auditIssues()" because the return value of "burp.api.montoya.scanner.ScanCheck.activeAudit(burp.api.montoya.http.message.HttpRequestResponse, burp.api.montoya.scanner.audit.insertionpoint.AuditInsertionPoint)" is null
	at burp.Zm23.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
java.lang.IllegalArgumentException: HTTP service cannot be null
	at burp.Zij2.ZI(Unknown Source)
	at burp.Zij2.sendRequest(Unknown Source)
	at burp.Zij2.sendRequest(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zx_5.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy58.sendRequest(Unknown Source)
	at burp.Zk78.sendRequest(Unknown Source)
	at BurpExtension.JWTScanCheck.activeAudit(JWTScanCheck.java:59)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zx_5.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy56.activeAudit(Unknown Source)
	at burp.Zm23.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
java.lang.IllegalArgumentException: HTTP service cannot be null
	at burp.Zij2.ZI(Unknown Source)
	at burp.Zij2.sendRequest(Unknown Source)
	at burp.Zij2.sendRequest(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zx_5.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy58.sendRequest(Unknown Source)
	at burp.Zk78.sendRequest(Unknown Source)
	at BurpExtension.JWTScanCheck.activeAudit(JWTScanCheck.java:59)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zx_5.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy56.activeAudit(Unknown Source)
	at burp.Zm23.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
java.lang.NullPointerException: Cannot invoke "burp.api.montoya.scanner.AuditResult.auditIssues()" because the return value of "burp.api.montoya.scanner.ScanCheck.activeAudit(burp.api.montoya.http.message.HttpRequestResponse, burp.api.montoya.scanner.audit.insertionpoint.AuditInsertionPoint)" is null
	at burp.Zm23.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
java.lang.IllegalArgumentException: HTTP service cannot be null
	at burp.Zij2.ZI(Unknown Source)
	at burp.Zij2.sendRequest(Unknown Source)
	at burp.Zij2.sendRequest(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zx_5.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy58.sendRequest(Unknown Source)
	at burp.Zk78.sendRequest(Unknown Source)
	at BurpExtension.JWTScanCheck.activeAudit(JWTScanCheck.java:59)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zx_5.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy56.activeAudit(Unknown Source)
	at burp.Zm23.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
java.lang.IllegalArgumentException: HTTP service cannot be null
	at burp.Zij2.ZI(Unknown Source)
	at burp.Zij2.sendRequest(Unknown Source)
	at burp.Zij2.sendRequest(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zx_5.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy58.sendRequest(Unknown Source)
	at burp.Zk78.sendRequest(Unknown Source)
	at BurpExtension.JWTScanCheck.activeAudit(JWTScanCheck.java:59)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zx_5.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy56.activeAudit(Unknown Source)
	at burp.Zm23.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
java.lang.NullPointerException: Cannot invoke "burp.api.montoya.scanner.AuditResult.auditIssues()" because the return value of "burp.api.montoya.scanner.ScanCheck.activeAudit(burp.api.montoya.http.message.HttpRequestResponse, burp.api.montoya.scanner.audit.insertionpoint.AuditInsertionPoint)" is null
	at burp.Zm23.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583) 

<img width="1543" alt="Screenshot 2024-04-23 at 09 47 40" src="https://github.com/CompassSecurity/jwt-scanner/assets/1572822/4f8e506b-45d7-4718-aa8e-4396ec058568">

**Comment by bcyrill** [comment]
Thank you for your report. The issue should be addressed in release 1.0.1. https://github.com/CompassSecurity/jwt-scanner/releases/tag/1.0.1

**Comment by Teicu** [comment]
Hello, 

I still get some errors 


No JWT found.
No JWT found.
No JWT found.
No JWT found.
No JWT found.
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143)
	at BurpExtension.ContextMenu.provideMenuItems(ContextMenu.java:60)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zx_5.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy50.provideMenuItems(Unknown Source)
	at burp.Zxj3.ZG(Unknown Source)
	at burp.Zdj7.ZX(Unknown Source)
	at burp.Zbn8.ZC(Unknown Source)
	at burp.Zbn8.Zx(Unknown Source)
	at burp.Zbn8.Zp(Unknown Source)
	at burp.Zbn8.ZF(Unknown Source)
	at burp.Zk01.ZN(Unknown Source)
	at burp.Zmi8.Zf(Unknown Source)
	at burp.Zr98.Zg(Unknown Source)
	at burp.Zr98.mousePressed(Unknown Source)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6618)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
	at java.desktop/java.awt.Component.processEvent(Component.java:6386)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4996)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4572)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at burp.Zudq.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
No JWT found.
java.lang.StringIndexOutOfBoundsException: Range [1249, 641) out of bounds for length 641
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4861)
	at java.base/java.lang.String.substring(String.java:2830)
	at BurpExtension.JwtInsertionPoint.<init>(JwtInsertionPoint.java:52)
	at BurpExtension.ContextMenu.provideMenuItems(ContextMenu.java:65)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zx_5.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy50.provideMenuItems(Unknown Source)
	at burp.Zxj3.ZG(Unknown Source)
	at burp.Zdj7.ZX(Unknown Source)
	at burp.Zbn8.ZC(Unknown Source)
	at burp.Zbn8.Zx(Unknown Source)
	at burp.Zbn8.Zp(Unknown Source)
	at burp.Zbn8.ZF(Unknown Source)
	at burp.Zbn8.ZT(Unknown Source)
	at burp.Zuv2.ZG(Unknown Source)
	at burp.Zxmu.ZH(Unknown Source)
	at burp.Zxmu.ZM(Unknown Source)
	at burp.Zxmu.mousePressed(Unknown Source)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6618)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
	at java.desktop/java.awt.Component.processEvent(Component.java:6386)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4996)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4572)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at burp.Zudq.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by bcyrill** [comment]
Thank you. The issue regarding the Context Menu should now be addressed as well.

**Comment by Teicu** [comment]
> Thank you. The issue regarding the Context Menu should now be addressed as well.

Hello, 

I keep getting these errors when using the latest version, any idea why? 

at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zdjo.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy197.activeAudit(Unknown Source)
	at burp.Zger.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
java.lang.IllegalArgumentException: HTTP service cannot be null
	at burp.Zfv4.ZM(Unknown Source)
	at burp.Zfv4.sendRequest(Unknown Source)
	at burp.Zfv4.sendRequest(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zdjo.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy57.sendRequest(Unknown Source)
	at burp.Ztg.sendRequest(Unknown Source)
	at BurpExtension.JWTScanCheck.activeAudit(JWTScanCheck.java:60)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zdjo.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy197.activeAudit(Unknown Source)
	at burp.Zger.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
java.lang.NullPointerException
java.lang.IllegalArgumentException: HTTP service cannot be null
	at burp.Zfv4.ZM(Unknown Source)
	at burp.Zfv4.sendRequest(Unknown Source)
	at burp.Zfv4.sendRequest(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zdjo.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy57.sendRequest(Unknown Source)
	at burp.Ztg.sendRequest(Unknown Source)
	at BurpExtension.JWTScanCheck.activeAudit(JWTScanCheck.java:60)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zdjo.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy197.activeAudit(Unknown Source)
	at burp.Zger.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
java.lang.IllegalArgumentException: HTTP service cannot be null
	at burp.Zfv4.ZM(Unknown Source)
	at burp.Zfv4.sendRequest(Unknown Source)
	at burp.Zfv4.sendRequest(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zdjo.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy57.sendRequest(Unknown Source)
	at burp.Ztg.sendRequest(Unknown Source)
	at BurpExtension.JWTScanCheck.activeAudit(JWTScanCheck.java:60)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zdjo.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy197.activeAudit(Unknown Source)
	at burp.Zger.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
java.lang.NullPointerException
java.lang.IllegalArgumentException: HTTP service cannot be null
	at burp.Zfv4.ZM(Unknown Source)
	at burp.Zfv4.sendRequest(Unknown Source)
	at burp.Zfv4.sendRequest(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zdjo.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy57.sendRequest(Unknown Source)
	at burp.Ztg.sendRequest(Unknown Source)
	at BurpExtension.JWTScanCheck.activeAudit(JWTScanCheck.java:60)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zdjo.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy197.activeAudit(Unknown Source)
	at burp.Zger.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
java.lang.IllegalArgumentException: HTTP service cannot be null
	at burp.Zfv4.ZM(Unknown Source)
	at burp.Zfv4.sendRequest(Unknown Source)
	at burp.Zfv4.sendRequest(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zdjo.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy57.sendRequest(Unknown Source)
	at burp.Ztg.sendRequest(Unknown Source)
	at BurpExtension.JWTScanCheck.activeAudit(JWTScanCheck.java:60)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zdjo.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy197.activeAudit(Unknown Source)
	at burp.Zger.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
java.lang.NullPointerException
java.lang.IllegalArgumentException: HTTP service cannot be null
	at burp.Zfv4.ZM(Unknown Source)
	at burp.Zfv4.sendRequest(Unknown Source)
	at burp.Zfv4.sendRequest(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zdjo.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy57.sendRequest(Unknown Source)
	at burp.Ztg.sendRequest(Unknown Source)
	at BurpExtension.JWTScanCheck.activeAudit(JWTScanCheck.java:60)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zdjo.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy197.activeAudit(Unknown Source)
	at burp.Zger.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
java.lang.IllegalArgumentException: HTTP service cannot be null
	at burp.Zfv4.ZM(Unknown Source)
	at burp.Zfv4.sendRequest(Unknown Source)
	at burp.Zfv4.sendRequest(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zdjo.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy57.sendRequest(Unknown Source)
	at burp.Ztg.sendRequest(Unknown Source)
	at BurpExtension.JWTScanCheck.activeAudit(JWTScanCheck.java:60)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zdjo.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy197.activeAudit(Unknown Source)
	at burp.Zger.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
java.lang.NullPointerException 

<img width="1293" alt="Screenshot 2024-05-08 at 09 53 37" src="https://github.com/CompassSecurity/jwt-scanner/assets/1572822/4d7db720-ef36-4637-85e8-890055da5b9e">

**Comment by bcyrill** [comment]
Thank you. I updated the code to ensure a copy of the HttpRequest is created. I believe this should address the issue that the HTTP service was null in certain cases. Let me know if you still experience any issues.
